### Crear Etiqueta (POST) ###
POST http://localhost:8080//api/v1/etiqueta
Content-Type: application/json

{
  "title": "Nueva Etiqueta2"
}

### Obtener Todas las Etiquetas (GET) ###
GET http://localhost:8080/api/v1/alletiqueta

### Obtener Etiqueta por ID (GET) ###
GET http://localhost:8080/api/v1/Idetiqueta/2

### Actualizar Etiqueta por ID (PUT) ###
PUT http://localhost:8080/api/v1/update/2
Content-Type: application/json

{
  "title": "Etiqueta Actualizada"
}

### Eliminar Etiqueta por ID (DELETE) ###
DELETE http://localhost:8080/api/v1/delete/3