#Solicitud para crear una nueva tarea
POST http://localhost:8080/api/v1/create
Content-Type: application/json

{
  "description": "Nueva tarea",
  "date": "30-09-2023",
  "status": true,
  "labelIds": [1,2]
}
###
#Listar Task
GET http://localhost:8080/api/v1/alltask

###
#Actualizar una tarea por su ID (PUT):
PUT http://localhost:8080/api/v1/update/{{id}}
Content-Type: application/json

{
  "taskId": 1,
  "description": "Tarea actualizada",
  "date": "2023-10-01",
  "status": true,
  "labelIds": [4, 5]
}

###
#Eliminar una tarea por su ID (DELETE):
DELETE http://localhost:8080/api/v1/delete/{{id}}

