#Solicitud para crear una nueva tarea
POST http://localhost:8080/api/v1/createNew
Content-Type: application/json

{
  "date": "2023-09-23T12:00:00Z",
  "description": "Nueva tarea 2",
  "status": false,
  "labels": [1]
}
###
#Listar Task
GET http://localhost:8080/api/v1/alltask

###
#Actualizar una tarea por su ID (PUT):
PUT http://localhost:8080/api/updatetask/2
Content-Type: application/json

{
  "date": "2023-10-01",
  "description": "Tarea actualizada",
  "status": true,
  "labelIds": [4, 5]
}

###
#Eliminar una tarea por su ID (DELETE):
DELETE http://localhost:8080/api/v1/delete/1

